### PR TITLE
Update numpy

### PR DESCRIPTION
**Pull request by cvfosammmm**

### CODE REVIEW

**Comment by cvfosammmm** [comment]
Not sure what went wrong here.

**Comment by hfiguiere** [comment]
`numpy` seems to require `tomli`.

**Comment by cvfosammmm** [comment]
Ok. Do you know why version 60 (latest commit) isn't published yet?

**Comment by hfiguiere** [comment]
> Ok. Do you know why version 60 (latest commit) isn't published yet?

no idea, it should have been.

**Comment by cvfosammmm** [comment]
Ideas about the latest failure?

**Comment by hfiguiere** [comment]
not more than the log says. Some python package isn't found. My take is as follow: is the numpy update needed? If not, then to skip it.

**Comment by cvfosammmm** [comment]
ok

**Pull request closed without merging**
