### PR TITLE
Bumping the org.gnome.Platform version

### PR DESCRIPTION
**Pull request by RobusTetus**
See #47

### CODE REVIEW

**Comment by 0unknwn** [comment]
Please revert this commit as it breaks the ability to compile with XeLaTeX. See: https://github.com/cvfosammmm/Setzer/issues/409#issue-2349692607

**Comment by hfiguiere** [comment]
the problem is the extension version should have been changed to 23.08 and this wasn't.

**Comment by 0unknwn** [comment]
Could we run some tests before we publish Setzer on Flathub? I would be happy to volunteer for this. I broken LaTeX application can be a very bad thing. Think of math students who have to submit a paper and miss the deadline because their document doesn't compile.

**Comment by hfiguiere** [comment]
Then maybe you can help test the build at https://github.com/flathub/org.cvfosammmm.Setzer/pull/50#issuecomment-2169584850

**Comment by 0unknwn** [comment]
Sure, will do! Thanks for your work!

**Pull request merged**
