### PR TITLE
Remove perl

### PR DESCRIPTION
**Pull request by jakobjakobson13**
as it is already provided by the texlive extension

### CODE REVIEW

**Comment by cvfosammmm** [comment]
I think Latexmk depends on it. Can you test if it still works without Perl?

**Comment by jakobjakobson13** [comment]
> I think Latexmk depends on it. Can you test if it still works without Perl?

Right, there were some issues:
https://github.com/flathub/org.texstudio.TeXstudio/issues/28
https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/2

But I guess there should be a solution without rebuilding perl. I'll think about it later.

**Comment by jakobjakobson13** [comment]
> Build [11339 successful](https://flathub.org/builds/#/builders/32/builds/11339)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/10804/org.cvfosammmm.Setzer.flatpakref
> ```

Well, you are right. Latexmk does not work in this build.

**Comment by jakobjakobson13** [comment]
Also the functions `start_wizard`, `on_save_as_clicked`, `on_save_as_clicked` and `on_save_button_click` did not work. But I don't know if this is related to perl. I attached the output anyway.

```bash
Traceback (most recent call last):
  File "/app/bin/workspace/workspace_controller.py", line 100, in new_function
    return original_function(self, *args, **kwargs)
  File "/app/bin/workspace/workspace_controller.py", line 325, in start_wizard
    ServiceLocator.get_dialog('document_wizard').run(document)
  File "/app/bin/dialogs/document_wizard/document_wizard.py", line 74, in run
    self.goto_page(0)
  File "/app/bin/dialogs/document_wizard/document_wizard.py", line 186, in goto_page
    self.pages[page_number].on_activation()
  File "/app/bin/dialogs/document_wizard/pages/page_document_class.py", line 50, in on_activation
    GLib.idle_add(self.view.list.get_selected_row().grab_focus)
AttributeError: 'NoneType' object has no attribute 'grab_focus'
```

```bash
Traceback (most recent call last):
  File "/app/bin/workspace/workspace_controller.py", line 100, in new_function
    return original_function(self, *args, **kwargs)
  File "/app/bin/workspace/workspace_controller.py", line 173, in on_save_as_clicked
    filename = document.get_filename().rsplit('/', 1)[1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
```
```bash
Traceback (most recent call last):
  File "/app/bin/workspace/workspace_controller.py", line 100, in new_function
    return original_function(self, *args, **kwargs)
  File "/app/bin/workspace/workspace_controller.py", line 162, in on_save_button_click
    self.on_save_as_clicked()
  File "/app/bin/workspace/workspace_controller.py", line 100, in new_function
    return original_function(self, *args, **kwargs)
  File "/app/bin/workspace/workspace_controller.py", line 173, in on_save_as_clicked
    filename = document.get_filename().rsplit('/', 1)[1]
AttributeError: 'NoneType' object has no attribute 'rsplit'
```

**Comment by cvfosammmm** [comment]
These errors are not related to Perl, but thanks a lot for reporting them. They are now fixed in master.

I'm closing the PR for now. Feel free to open a new one when you found a solution.

**Pull request closed without merging**
